# ==================== CANCER CARE PORTAL ====================
CANCER_DATA = {
    "breast-cancer": {
        "name": "Breast Cancer",
        "category": "womens_health",
        "category_label": "Women's Health",
        "icon": "fa-ribbon",
        "image": "https://images.unsplash.com/photo-1579684385127-1ef15d508118?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        "description": "Malignancy forming in the breast ductal or lobular tissue, predominantly affecting women and occasionally men.",
        "symptoms": ["Painless palpable lump or thickening", "Change in breast size, contour, or symmetry", "Nipple inversion, discharge, or flaking", "Skin dimpling (peau d'orange)"],
        "risk_factors": ["Advancing age (>50)", "Family history (First-degree relative)", "BRCA1 / BRCA2 pathogenic variants", "Early menarche / late menopause", "Hormone replacement therapy"],
        "prevention": ["Annual 3D Digital Mammography (Ages 40+)", "Clinical breast examination", "Maintain healthy BMI & weekly aerobic activity", "Limit alcohol consumption"],
        "treatments": ["Breast-conserving surgery (Lumpectomy) or Mastectomy", "Targeted Monoclonal Antibodies", "Adjuvant / Neo-adjuvant Chemotherapy", "Hormonal Endocrine Blockers"],
        "key_biomarkers": ["HER2/neu (ERBB2)", "Estrogen Receptor (ER)", "Progesterone Receptor (PR)", "Ki-67 Proliferation", "BRCA1 / BRCA2"],
        "screening_test": "Annual 3D Digital Mammogram + Ultrasound for dense tissue",
        "common_drugs": ["Trastuzumab (Herceptin)", "Tamoxifen", "Anastrozole", "Paclitaxel", "Pembrolizumab"],
        "survival_rate_5yr": "91% overall, >99% if detected at localized stage"
    },
    "lung-cancer": {
        "name": "Lung Cancer (NSCLC / SCLC)",
        "category": "respiratory",
        "category_label": "Thoracic & Respiratory",
        "icon": "fa-lungs",
        "image": "https://images.unsplash.com/photo-1584036561566-baf8f5f1b144?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        "description": "Primary pulmonary malignancy originating in bronchial epithelial cells, categorized into Non-Small Cell (NSCLC) and Small Cell (SCLC).",
        "symptoms": ["Persistent dry or productive cough > 3 weeks", "Hemoptysis (coughing up blood)", "Progressive dyspnea & chest pain", "Hoarseness and recurrent pneumonia", "Unexplained weight loss"],
        "risk_factors": ["Active or heavy secondhand cigarette smoking", "Radon gas exposure in indoor spaces", "Occupational asbestos / silica exposure", "Pre-existing pulmonary fibrosis"],
        "prevention": ["Smoking cessation programs", "Radon level testing in homes", "Industrial respiratory protection", "Annual Low-Dose CT (LDCT) for high-risk smokers"],
        "treatments": ["Video-Assisted Thoracoscopic Surgery (VATS)", "Stereotactic Body Radiotherapy (SBRT)", "Tyrosine Kinase Inhibitors (TKIs)", "Immune Checkpoint Blockade"],
        "key_biomarkers": ["EGFR Mutation (Exon 19/21)", "ALK Translocation", "ROS1", "BRAF V600E", "PD-L1 Expression (%)"],
        "screening_test": "Annual Low-Dose Computed Tomography (LDCT) for 50-80 yr old smokers",
        "common_drugs": ["Osimertinib (Tagrisso)", "Pembrolizumab (Keytruda)", "Cisplatin / Etoposide", "Alectinib"],
        "survival_rate_5yr": "25% overall, 63% if diagnosed at localized stage"
    },
    "prostate-cancer": {
        "name": "Prostate Cancer",
        "category": "mens_health",
        "category_label": "Men's Health",
        "icon": "fa-mars",
        "image": "https://images.unsplash.com/photo-1530497610245-94d3c16cda28?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        "description": "Adenocarcinoma arising in the peripheral zone of the prostate gland, often slow-growing with high long-term cure rates.",
        "symptoms": ["Urinary hesitancy or weak stream", "Nocturia (frequent nighttime urination)", "Hematuria or hematospermia", "Pelvic or lower back bone discomfort"],
        "risk_factors": ["Age > 50 years", "African ancestry (higher incidence & aggressive biology)", "First-degree family history", "Germline DNA repair mutations (BRCA2, ATM)"],
        "prevention": ["Baseline PSA screening at age 45-50", "Mediterranean diet rich in lycopene & polyphenols", "Regular cardiovascular exercise", "Maintain healthy weight"],
        "treatments": ["Active Surveillance with multiparametric MRI", "Robot-Assisted Radical Prostatectomy", "Intensity-Modulated Radiation (IMRT) / Brachytherapy", "Androgen Deprivation Therapy (ADT)"],
        "key_biomarkers": ["Total & Free PSA (ng/mL)", "Gleason Score / Grade Group", "PSMA Expression", "BRCA2 / ATM Mutation"],
        "screening_test": "Serum PSA (Prostate-Specific Antigen) + Digital Rectal Exam (DRE)",
        "common_drugs": ["Leuprolide (Lupron)", "Enzalutamide (Xtandi)", "Abiraterone", "Docetaxel", "Pluvicto (Lu-177 PSMA)"],
        "survival_rate_5yr": "97% overall, >99% if localized or regional"
    },
    "colorectal-cancer": {
        "name": "Colorectal Cancer",
        "category": "gastrointestinal",
        "category_label": "Gastrointestinal",
        "icon": "fa-dna",
        "image": "https://images.unsplash.com/photo-1559757175-5700dde675bc?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        "description": "Malignant transformation of adenomatous or serrated polyps in the colon or rectum lumen.",
        "symptoms": ["Persistent alteration in bowel habits (diarrhea/constipation)", "Occult or frank rectal bleeding / dark stool", "Cramping abdominal pain & fullness", "Iron-deficiency anemia of unknown origin"],
        "risk_factors": ["Age > 45", "Lynch Syndrome (HNPCC) or FAP", "Inflammatory Bowel Disease (Crohn's, Ulcerative Colitis)", "High processed meat / low fiber diet"],
        "prevention": ["Routine screening colonoscopy starting at 45", "Polypectomy of precancerous lesions", "High-fiber nutrition and hydration", "Regular physical activity"],
        "treatments": ["Laparoscopic / Robotic Colectomy", "Adjuvant FOLFOX / CAPOX Chemotherapy", "Neoadjuvant Chemoradiation for rectal cancer", "Anti-VEGF & Anti-EGFR targeted therapy"],
        "key_biomarkers": ["MSI (Microsatellite Instability) / dMMR", "KRAS / NRAS Exon 2-4", "BRAF V600E", "HER2 Amplification"],
        "screening_test": "Colonoscopy every 10 years (or annual FIT stool test) starting at 45",
        "common_drugs": ["Oxaliplatin", "Fluorouracil (5-FU)", "Capecitabine", "Bevacizumab (Avastin)", "Pembrolizumab"],
        "survival_rate_5yr": "65% overall, 91% if diagnosed prior to node metastasis"
    },
    "skin-cancer-melanoma": {
        "name": "Melanoma & Skin Cancer",
        "category": "dermatology",
        "category_label": "Dermatology",
        "icon": "fa-sun",
        "image": "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        "description": "High-grade neoplasm of epidermal melanocytes, capable of rapid hematogenous and lymphatic dissemination.",
        "symptoms": ["Asymmetry in existing or new moles (ABCDE criteria)", "Border irregularity / scalloped edges", "Color variation (multiple shades of brown, black, blue, red)", "Diameter > 6mm or rapid enlargement", "Evolving shape, elevation, or bleeding"],
        "risk_factors": ["Excessive solar UV radiation & sunburn history", "Indoor tanning bed exposure", "Fitzpatrick Skin Types I-II (fair, freckled)", ">50 dysplastic nevi", "Immunosuppression"],
        "prevention": ["Broad-spectrum SPF 50+ sunscreen application", "Protective UV-rated clothing & wide-brim hats", "Avoid peak sunlight (10am-4pm)", "Quarterly self-examinations & annual full-body dermoscopy"],
        "treatments": ["Wide Local Excision with Sentinel Node Biopsy", "Dual Immune Checkpoint Inhibitors", "BRAF/MEK Targeted Combination Therapy", "Adjuvant Immunotherapy"],
        "key_biomarkers": ["BRAF V600E / V600K Mutation", "NRAS Mutation", "c-KIT Mutation", "PD-L1 Status"],
        "screening_test": "Annual Full-Body Skin Exam + Digital Dermatoscopy Mole Mapping",
        "common_drugs": ["Nivolumab (Opdivo)", "Pembrolizumab", "Ipilimumab (Yervoy)", "Dabrafenib + Trametinib"],
        "survival_rate_5yr": "94% overall, >99% if detected at Stage I"
    },
    "leukemia": {
        "name": "Leukemia (AML / ALL / CML / CLL)",
        "category": "hematology",
        "category_label": "Hematology & Blood",
        "icon": "fa-droplet",
        "image": "https://images.unsplash.com/photo-1579154204601-01588f351e67?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        "description": "Hematologic malignancies originating in bone marrow pluripotent stem cells, disrupting normal erythrocyte, leukocyte, and thrombocyte generation.",
        "symptoms": ["Profound refractory fatigue & pallor", "Petechiae, spontaneous ecchymosis, or mucosal bleeding", "Recurrent severe infections & unexplained febrile spikes", "Painless cervical/axillary lymphadenopathy", "Splenomegaly causing early satiety"],
        "risk_factors": ["Prior alkylating chemotherapy or ionizing radiation", "Exposure to benzene and industrial solvents", "Congenital syndromes (Trisomy 21, Fanconi anemia)", "Clonal hematopoiesis (CHIP)"],
        "prevention": ["Minimization of benzene & occupational chemical contact", "Radiation safety compliance", "Early diagnostic evaluation of unexplained cytopenias"],
        "treatments": ["Induction & Consolidation Chemotherapy (7+3 regimen)", "Allogeneic Hematopoietic Stem Cell Transplant (HSCT)", "Targeted Tyrosine Kinase Inhibitors for BCR-ABL", "CAR-T Cell Cellular Immunotherapy"],
        "key_biomarkers": ["Philadelphia Chromosome / BCR-ABL1", "FLT3-ITD / TKD", "NPM1", "TP53", "IDH1 / IDH2 Mutations"],
        "screening_test": "Complete Blood Count (CBC) with Differential + Peripheral Blood Smear",
        "common_drugs": ["Imatinib (Gleevec)", "Venetoclax", "Cytarabine", "Azacitidine", "Tisagenlecleucel (Kymriah)"],
        "survival_rate_5yr": "66% overall (varies by subtype: CLL >88%, AML ~32%)"
    },
    "pancreatic-cancer": {
        "name": "Pancreatic Adenocarcinoma",
        "category": "gastrointestinal",
        "category_label": "Gastrointestinal",
        "icon": "fa-flask-vial",
        "image": "https://images.unsplash.com/photo-1576086213369-97a306d36557?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        "description": "Highly aggressive malignancy predominantly arising in the exocrine ductal epithelium of the pancreatic head or body.",
        "symptoms": ["Painless progressive jaundice with dark urine & clay stool", "Midepigastric abdominal pain radiating to back", "Recent onset atypical diabetes in elderly", "Profound anorexia and rapid cachexia"],
        "risk_factors": ["Chronic pancreatitis & intraductal papillary mucinous neoplasms (IPMN)", "Cigarette smoking (2-fold risk)", "Hereditary pancreatitis (PRSS1) & BRCA2 mutations", "High-fat diet & obesity"],
        "prevention": ["Smoking cessation", "Endoscopic ultrasound (EUS) screening in hereditary carriers", "Healthy metabolic profile & low-sugar Mediterranean diet"],
        "treatments": ["Pancreaticoduodenectomy (Whipple Procedure)", "Neoadjuvant / Adjuvant FOLFIRINOX or Gemcitabine+Nab-Paclitaxel", "Stereotactic Body Radiotherapy (SBRT)", "PARP Inhibitor Maintenance for BRCA carriers"],
        "key_biomarkers": ["CA 19-9 Serum Marker", "KRAS Mutation (>90%)", "BRCA1 / BRCA2 Germline", "MSI Status"],
        "screening_test": "Endoscopic Ultrasound (EUS) & Pancreatic-Protocol Triphasic CT for high-risk cohorts",
        "common_drugs": ["FOLFIRINOX (5-FU, Leucovorin, Irinotecan, Oxaliplatin)", "Gemcitabine", "Abraxane", "Olaparib (Lynparza)"],
        "survival_rate_5yr": "13% overall, 44% if localized and surgically resectable"
    },
    "ovarian-cancer": {
        "name": "Ovarian & GYN Oncology",
        "category": "womens_health",
        "category_label": "Women's Health",
        "icon": "fa-venus",
        "image": "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        "description": "High-grade serous epithelial carcinomas arising in the fallopian tubes or ovarian surface, frequently diagnosed at advanced stages.",
        "symptoms": ["Persistent abdominal bloating & pelvic fullness", "Early satiety / difficulty eating", "Increased urinary frequency or urgency", "Unexplained pelvic discomfort or post-menopausal bleeding"],
        "risk_factors": ["BRCA1 or BRCA2 germline pathogenic mutations", "Lynch syndrome (HNPCC)", "Nulliparity (never having carried a pregnancy)", "Endometriosis"],
        "prevention": ["Risk-reducing bilateral salpingo-oophorectomy in BRCA carriers", "Oral contraceptive use (>5 years reduces risk up to 50%)", "Genetic counseling and testing"],
        "treatments": ["Maximal Cytoreductive Debulking Surgery (Optimal residual < 1cm)", "Intraperitoneal / Intravenous Carboplatin + Paclitaxel", "PARP Inhibitor Maintenance", "Anti-angiogenic therapy"],
        "key_biomarkers": ["CA-125 Serum Marker", "Homologous Recombination Deficiency (HRD)", "BRCA1 / BRCA2", "HER2 / TP53"],
        "screening_test": "Transvaginal Ultrasound (TVUS) + CA-125 level in high-risk hereditary patients",
        "common_drugs": ["Carboplatin + Paclitaxel", "Olaparib", "Niraparib (Zejula)", "Bevacizumab"],
        "survival_rate_5yr": "51% overall, 93% if detected when confined to ovaries"
    },
    "lymphoma": {
        "name": "Lymphoma (Hodgkin & Non-Hodgkin)",
        "category": "hematology",
        "category_label": "Hematology & Blood",
        "icon": "fa-shield-halved",
        "image": "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        "description": "Neoplasms originating in mature B, T, or Natural Killer (NK) lymphocytes in lymph nodes, spleen, or extranodal lymphatic tissues.",
        "symptoms": ["Painless enlargement of lymph nodes in neck, armpit, or groin", "B-Symptoms: Drenching night sweats, fever >38°C, weight loss >10%", "Generalized pruritus (severe itching)", "Chest pressure or persistent dry cough"],
        "risk_factors": ["Epstein-Barr Virus (EBV), H. pylori, or HIV infection", "Immunosuppressive medication post-transplant", "Autoimmune disorders (Rheumatoid arthritis, Sjögren's)", "Pesticide & herbicide exposure"],
        "prevention": ["Treatment of chronic H. pylori infection (MALT lymphoma)", "Protection against immunosuppressive exposures", "Prompt evaluation of persistent lymphadenopathy"],
        "treatments": ["ABVD Chemotherapy (Hodgkin)", "R-CHOP Immunochemotherapy (DLBCL / Non-Hodgkin)", "Involved-Site Radiotherapy (ISRT)", "Autologous / Allogeneic Stem Cell Transplant & CAR-T Therapy"],
        "key_biomarkers": ["CD20 Expression", "CD30 / CD15 (Reed-Sternberg Cells)", "MYC, BCL2, BCL6 Rearrangements", "Ki-67 Index"],
        "screening_test": "Excisional Lymph Node Biopsy + Whole-Body FDG PET-CT Staging",
        "common_drugs": ["Rituximab (Rituxan)", "Brentuximab Vedotin", "Polatuzumab", "CHOP Chemotherapy", "Axicabtagene (Yescarta)"],
        "survival_rate_5yr": "89% for Hodgkin Lymphoma, 74% for Non-Hodgkin Lymphoma"
    },
    "brain-tumor-glioblastoma": {
        "name": "Brain & CNS Tumors (Glioblastoma)",
        "category": "neurology",
        "category_label": "Neurology & CNS",
        "icon": "fa-brain",
        "image": "https://images.unsplash.com/photo-1559757175-0eb30cd8c063?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        "description": "Primary central nervous system tumors including IDH-wildtype Glioblastoma (Grade IV Astrocytoma) with invasive microvascular proliferation.",
        "symptoms": ["New onset severe morning headaches with nausea", "Focal motor weakness, hemiparesis, or speech dysphasia", "Unprovoked seizures in adult patients", "Personality, cognitive, or behavioral alterations"],
        "risk_factors": ["Prior cranial ionizing radiotherapy", "Rare genetic syndromes (Li-Fraumeni, Neurofibromatosis Type 1/2)", "Age peak between 55-75 years"],
        "prevention": ["Avoidance of unnecessary high-dose head radiation", "Early neuroimaging for unexplained progressive neurologic deficits"],
        "treatments": ["Maximal Safe Surgical Resection with intraoperative 5-ALA fluorescence", "Stupp Protocol: Concurrent Temozolomide + Radiotherapy", "Tumor Treating Fields (Optune TTFields)", "Anti-VEGF therapy"],
        "key_biomarkers": ["MGMT Promoter Methylation", "IDH1 / IDH2 Mutation", "1p/19q Co-deletion", "EGFRvIII Amplification"],
        "screening_test": "Brain MRI with and without Gadolinium Contrast + Perfusion Protocol",
        "common_drugs": ["Temozolomide (Temodar)", "Bevacizumab (Avastin)", "Lomustine (CCNU)", "Dexamethasone"],
        "survival_rate_5yr": "5-Year Overall Survival ~7% for Glioblastoma, >60% for Low-Grade IDH-mutant Gliomas"
    }
}
