"""
Spherix Clinic - Comprehensive 195 Sovereign Countries Dataset
Contains all 193 UN Member States + 2 UN Observer States (Holy See and State of Palestine),
complete with native flags, ISO alpha codes, currencies, and timezones.
"""

COUNTRIES_195 = [
    {"name": "Afghanistan", "code": "AF", "flag": "🇦🇫", "currency": "AFN", "timezone": "AFT (UTC+4:30)"},
    {"name": "Albania", "code": "AL", "flag": "🇦🇱", "currency": "ALL", "timezone": "CET (UTC+1:00)"},
    {"name": "Algeria", "code": "DZ", "flag": "🇩🇿", "currency": "DZD", "timezone": "CET (UTC+1:00)"},
    {"name": "Andorra", "code": "AD", "flag": "🇦🇩", "currency": "EUR", "timezone": "CET (UTC+1:00)"},
    {"name": "Angola", "code": "AO", "flag": "🇦🇴", "currency": "AOA", "timezone": "WAT (UTC+1:00)"},
    {"name": "Antigua and Barbuda", "code": "AG", "flag": "🇦🇬", "currency": "XCD", "timezone": "AST (UTC-4:00)"},
    {"name": "Argentina", "code": "AR", "flag": "🇦🇷", "currency": "ARS", "timezone": "ART (UTC-3:00)"},
    {"name": "Armenia", "code": "AM", "flag": "🇦🇲", "currency": "AMD", "timezone": "AMT (UTC+4:00)"},
    {"name": "Australia", "code": "AU", "flag": "🇦🇺", "currency": "AUD", "timezone": "AEST (UTC+10:00)"},
    {"name": "Austria", "code": "AT", "flag": "🇦🇹", "currency": "EUR", "timezone": "CET (UTC+1:00)"},
    {"name": "Azerbaijan", "code": "AZ", "flag": "🇦🇿", "currency": "AZN", "timezone": "AZT (UTC+4:00)"},
    {"name": "Bahamas", "code": "BS", "flag": "🇧🇸", "currency": "BSD", "timezone": "EST (UTC-5:00)"},
    {"name": "Bahrain", "code": "BH", "flag": "🇧🇭", "currency": "BHD", "timezone": "AST (UTC+3:00)"},
    {"name": "Bangladesh", "code": "BD", "flag": "🇧🇩", "currency": "BDT", "timezone": "BST (UTC+6:00)"},
    {"name": "Barbados", "code": "BB", "flag": "🇧🇧", "currency": "BBD", "timezone": "AST (UTC-4:00)"},
    {"name": "Belarus", "code": "BY", "flag": "🇧🇾", "currency": "BYN", "timezone": "MSK (UTC+3:00)"},
    {"name": "Belgium", "code": "BE", "flag": "🇧🇪", "currency": "EUR", "timezone": "CET (UTC+1:00)"},
    {"name": "Belize", "code": "BZ", "flag": "🇧🇿", "currency": "BZD", "timezone": "CST (UTC-6:00)"},
    {"name": "Benin", "code": "BJ", "flag": "🇧🇯", "currency": "XOF", "timezone": "WAT (UTC+1:00)"},
    {"name": "Bhutan", "code": "BT", "flag": "🇧🇹", "currency": "BTN", "timezone": "BTT (UTC+6:00)"},
    {"name": "Bolivia", "code": "BO", "flag": "🇧🇴", "currency": "BOB", "timezone": "BOT (UTC-4:00)"},
    {"name": "Bosnia and Herzegovina", "code": "BA", "flag": "🇧🇦", "currency": "BAM", "timezone": "CET (UTC+1:00)"},
    {"name": "Botswana", "code": "BW", "flag": "🇧🇼", "currency": "BWP", "timezone": "CAT (UTC+2:00)"},
    {"name": "Brazil", "code": "BR", "flag": "🇧🇷", "currency": "BRL", "timezone": "BRT (UTC-3:00)"},
    {"name": "Brunei", "code": "BN", "flag": "🇧🇳", "currency": "BND", "timezone": "BNT (UTC+8:00)"},
    {"name": "Bulgaria", "code": "BG", "flag": "🇧🇬", "currency": "BGN", "timezone": "EET (UTC+2:00)"},
    {"name": "Burkina Faso", "code": "BF", "flag": "🇧🇫", "currency": "XOF", "timezone": "GMT (UTC+0:00)"},
    {"name": "Burundi", "code": "BI", "flag": "🇧🇮", "currency": "BIF", "timezone": "CAT (UTC+2:00)"},
    {"name": "Cabo Verde", "code": "CV", "flag": "🇨🇻", "currency": "CVE", "timezone": "CVT (UTC-1:00)"},
    {"name": "Cambodia", "code": "KH", "flag": "🇰🇭", "currency": "KHR", "timezone": "ICT (UTC+7:00)"},
    {"name": "Cameroon", "code": "CM", "flag": "🇨🇲", "currency": "XAF", "timezone": "WAT (UTC+1:00)"},
    {"name": "Canada", "code": "CA", "flag": "🇨🇦", "currency": "CAD", "timezone": "EST (UTC-5:00)"},
    {"name": "Central African Republic", "code": "CF", "flag": "🇨🇫", "currency": "XAF", "timezone": "WAT (UTC+1:00)"},
    {"name": "Chad", "code": "TD", "flag": "🇹🇩", "currency": "XAF", "timezone": "WAT (UTC+1:00)"},
    {"name": "Chile", "code": "CL", "flag": "🇨🇱", "currency": "CLP", "timezone": "CLT (UTC-4:00)"},
    {"name": "China", "code": "CN", "flag": "🇨🇳", "currency": "CNY", "timezone": "CST (UTC+8:00)"},
    {"name": "Colombia", "code": "CO", "flag": "🇨🇴", "currency": "COP", "timezone": "COT (UTC-5:00)"},
    {"name": "Comoros", "code": "KM", "flag": "🇰🇲", "currency": "KMF", "timezone": "EAT (UTC+3:00)"},
    {"name": "Congo (Congo-Brazzaville)", "code": "CG", "flag": "🇨🇬", "currency": "XAF", "timezone": "WAT (UTC+1:00)"},
    {"name": "Costa Rica", "code": "CR", "flag": "🇨🇷", "currency": "CRC", "timezone": "CST (UTC-6:00)"},
    {"name": "Croatia", "code": "HR", "flag": "🇭🇷", "currency": "EUR", "timezone": "CET (UTC+1:00)"},
    {"name": "Cuba", "code": "CU", "flag": "🇨🇺", "currency": "CUP", "timezone": "CST (UTC-5:00)"},
    {"name": "Cyprus", "code": "CY", "flag": "🇨🇾", "currency": "EUR", "timezone": "EET (UTC+2:00)"},
    {"name": "Czech Republic", "code": "CZ", "flag": "🇨🇿", "currency": "CZK", "timezone": "CET (UTC+1:00)"},
    {"name": "Democratic Republic of the Congo", "code": "CD", "flag": "🇨🇩", "currency": "CDF", "timezone": "WAT (UTC+1:00)"},
    {"name": "Denmark", "code": "DK", "flag": "🇩🇰", "currency": "DKK", "timezone": "CET (UTC+1:00)"},
    {"name": "Djibouti", "code": "DJ", "flag": "🇩🇯", "currency": "DJF", "timezone": "EAT (UTC+3:00)"},
    {"name": "Dominica", "code": "DM", "flag": "🇩🇲", "currency": "XCD", "timezone": "AST (UTC-4:00)"},
    {"name": "Dominican Republic", "code": "DO", "flag": "🇩🇴", "currency": "DOP", "timezone": "AST (UTC-4:00)"},
    {"name": "Ecuador", "code": "EC", "flag": "🇪🇨", "currency": "USD", "timezone": "ECT (UTC-5:00)"},
    {"name": "Egypt", "code": "EG", "flag": "🇪🇬", "currency": "EGP", "timezone": "EET (UTC+2:00)"},
    {"name": "El Salvador", "code": "SV", "flag": "🇸🇻", "currency": "USD", "timezone": "CST (UTC-6:00)"},
    {"name": "Equatorial Guinea", "code": "GQ", "flag": "🇬🇶", "currency": "XAF", "timezone": "WAT (UTC+1:00)"},
    {"name": "Eritrea", "code": "ER", "flag": "🇪🇷", "currency": "ERN", "timezone": "EAT (UTC+3:00)"},
    {"name": "Estonia", "code": "EE", "flag": "🇪🇪", "currency": "EUR", "timezone": "EET (UTC+2:00)"},
    {"name": "Eswatini", "code": "SZ", "flag": "🇸🇿", "currency": "SZL", "timezone": "SAST (UTC+2:00)"},
    {"name": "Ethiopia", "code": "ET", "flag": "🇪🇹", "currency": "ETB", "timezone": "EAT (UTC+3:00)"},
    {"name": "Fiji", "code": "FJ", "flag": "🇫🇯", "currency": "FJD", "timezone": "FJT (UTC+12:00)"},
    {"name": "Finland", "code": "FI", "flag": "🇫🇮", "currency": "EUR", "timezone": "EET (UTC+2:00)"},
    {"name": "France", "code": "FR", "flag": "🇫🇷", "currency": "EUR", "timezone": "CET (UTC+1:00)"},
    {"name": "Gabon", "code": "GA", "flag": "🇬🇦", "currency": "XAF", "timezone": "WAT (UTC+1:00)"},
    {"name": "Gambia", "code": "GM", "flag": "🇬🇲", "currency": "GMD", "timezone": "GMT (UTC+0:00)"},
    {"name": "Georgia", "code": "GE", "flag": "🇬🇪", "currency": "GEL", "timezone": "GET (UTC+4:00)"},
    {"name": "Germany", "code": "DE", "flag": "🇩🇪", "currency": "EUR", "timezone": "CET (UTC+1:00)"},
    {"name": "Ghana", "code": "GH", "flag": "🇬🇭", "currency": "GHS", "timezone": "GMT (UTC+0:00)"},
    {"name": "Greece", "code": "GR", "flag": "🇬🇷", "currency": "EUR", "timezone": "EET (UTC+2:00)"},
    {"name": "Grenada", "code": "GD", "flag": "🇬🇩", "currency": "XCD", "timezone": "AST (UTC-4:00)"},
    {"name": "Guatemala", "code": "GT", "flag": "🇬🇹", "currency": "GTQ", "timezone": "CST (UTC-6:00)"},
    {"name": "Guinea", "code": "GN", "flag": "🇬🇳", "currency": "GNF", "timezone": "GMT (UTC+0:00)"},
    {"name": "Guinea-Bissau", "code": "GW", "flag": "🇬🇼", "currency": "XOF", "timezone": "GMT (UTC+0:00)"},
    {"name": "Guyana", "code": "GY", "flag": "🇬🇾", "currency": "GYD", "timezone": "GYT (UTC-4:00)"},
    {"name": "Haiti", "code": "HT", "flag": "🇭🇹", "currency": "HTG", "timezone": "EST (UTC-5:00)"},
    {"name": "Holy See (Vatican City)", "code": "VA", "flag": "🇻🇦", "currency": "EUR", "timezone": "CET (UTC+1:00)"},
    {"name": "Honduras", "code": "HN", "flag": "🇭🇳", "currency": "HNL", "timezone": "CST (UTC-6:00)"},
    {"name": "Hungary", "code": "HU", "flag": "🇭🇺", "currency": "HUF", "timezone": "CET (UTC+1:00)"},
    {"name": "Iceland", "code": "IS", "flag": "🇮🇸", "currency": "ISK", "timezone": "GMT (UTC+0:00)"},
    {"name": "India", "code": "IN", "flag": "🇮🇳", "currency": "INR", "timezone": "IST (UTC+5:30)"},
    {"name": "Indonesia", "code": "ID", "flag": "🇮🇩", "currency": "IDR", "timezone": "WIB (UTC+7:00)"},
    {"name": "Iran", "code": "IR", "flag": "🇮🇷", "currency": "IRR", "timezone": "IRST (UTC+3:30)"},
    {"name": "Iraq", "code": "IQ", "flag": "🇮🇶", "currency": "IQD", "timezone": "AST (UTC+3:00)"},
    {"name": "Ireland", "code": "IE", "flag": "🇮🇪", "currency": "EUR", "timezone": "GMT (UTC+0:00)"},
    {"name": "Israel", "code": "IL", "flag": "🇮🇱", "currency": "ILS", "timezone": "IST (UTC+2:00)"},
    {"name": "Italy", "code": "IT", "flag": "🇮🇹", "currency": "EUR", "timezone": "CET (UTC+1:00)"},
    {"name": "Ivory Coast", "code": "CI", "flag": "🇨🇮", "currency": "XOF", "timezone": "GMT (UTC+0:00)"},
    {"name": "Jamaica", "code": "JM", "flag": "🇯🇲", "currency": "JMD", "timezone": "EST (UTC-5:00)"},
    {"name": "Japan", "code": "JP", "flag": "🇯🇵", "currency": "JPY", "timezone": "JST (UTC+9:00)"},
    {"name": "Jordan", "code": "JO", "flag": "🇯🇴", "currency": "JOD", "timezone": "AST (UTC+3:00)"},
    {"name": "Kazakhstan", "code": "KZ", "flag": "🇰🇿", "currency": "KZT", "timezone": "ALMT (UTC+5:00)"},
    {"name": "Kenya", "code": "KE", "flag": "🇰🇪", "currency": "KES", "timezone": "EAT (UTC+3:00)"},
    {"name": "Kiribati", "code": "KI", "flag": "🇰🇮", "currency": "AUD", "timezone": "GILT (UTC+12:00)"},
    {"name": "Kuwait", "code": "KW", "flag": "🇰🇼", "currency": "KWD", "timezone": "AST (UTC+3:00)"},
    {"name": "Kyrgyzstan", "code": "KG", "flag": "🇰🇬", "currency": "KGS", "timezone": "KGT (UTC+6:00)"},
    {"name": "Laos", "code": "LA", "flag": "🇱🇦", "currency": "LAK", "timezone": "ICT (UTC+7:00)"},
    {"name": "Latvia", "code": "LV", "flag": "🇱🇻", "currency": "EUR", "timezone": "EET (UTC+2:00)"},
    {"name": "Lebanon", "code": "LB", "flag": "🇱🇧", "currency": "LBP", "timezone": "EET (UTC+2:00)"},
    {"name": "Lesotho", "code": "LS", "flag": "🇱🇸", "currency": "LSL", "timezone": "SAST (UTC+2:00)"},
    {"name": "Liberia", "code": "LR", "flag": "🇱🇷", "currency": "LRD", "timezone": "GMT (UTC+0:00)"},
    {"name": "Libya", "code": "LY", "flag": "🇱🇾", "currency": "LYD", "timezone": "EET (UTC+2:00)"},
    {"name": "Liechtenstein", "code": "LI", "flag": "🇱🇮", "currency": "CHF", "timezone": "CET (UTC+1:00)"},
    {"name": "Lithuania", "code": "LT", "flag": "🇱🇹", "currency": "EUR", "timezone": "EET (UTC+2:00)"},
    {"name": "Luxembourg", "code": "LU", "flag": "🇱🇺", "currency": "EUR", "timezone": "CET (UTC+1:00)"},
    {"name": "Madagascar", "code": "MG", "flag": "🇲🇬", "currency": "MGA", "timezone": "EAT (UTC+3:00)"},
    {"name": "Malawi", "code": "MW", "flag": "🇲🇼", "currency": "MWK", "timezone": "CAT (UTC+2:00)"},
    {"name": "Malaysia", "code": "MY", "flag": "🇲🇾", "currency": "MYR", "timezone": "MYT (UTC+8:00)"},
    {"name": "Maldives", "code": "MV", "flag": "🇲🇻", "currency": "MVR", "timezone": "MVT (UTC+5:00)"},
    {"name": "Mali", "code": "ML", "flag": "🇲🇱", "currency": "XOF", "timezone": "GMT (UTC+0:00)"},
    {"name": "Malta", "code": "MT", "flag": "🇲🇹", "currency": "EUR", "timezone": "CET (UTC+1:00)"},
    {"name": "Marshall Islands", "code": "MH", "flag": "🇲🇭", "currency": "USD", "timezone": "MHT (UTC+12:00)"},
    {"name": "Mauritania", "code": "MR", "flag": "🇲🇷", "currency": "MRU", "timezone": "GMT (UTC+0:00)"},
    {"name": "Mauritius", "code": "MU", "flag": "🇲🇺", "currency": "MUR", "timezone": "MUT (UTC+4:00)"},
    {"name": "Mexico", "code": "MX", "flag": "🇲🇽", "currency": "MXN", "timezone": "CST (UTC-6:00)"},
    {"name": "Micronesia", "code": "FM", "flag": "🇫🇲", "currency": "USD", "timezone": "CHOT (UTC+11:00)"},
    {"name": "Moldova", "code": "MD", "flag": "🇲🇩", "currency": "MDL", "timezone": "EET (UTC+2:00)"},
    {"name": "Monaco", "code": "MC", "flag": "🇲🇨", "currency": "EUR", "timezone": "CET (UTC+1:00)"},
    {"name": "Mongolia", "code": "MN", "flag": "🇲🇳", "currency": "MNT", "timezone": "ULAT (UTC+8:00)"},
    {"name": "Montenegro", "code": "ME", "flag": "🇲🇪", "currency": "EUR", "timezone": "CET (UTC+1:00)"},
    {"name": "Morocco", "code": "MA", "flag": "🇲🇦", "currency": "MAD", "timezone": "WEST (UTC+1:00)"},
    {"name": "Mozambique", "code": "MZ", "flag": "🇲🇿", "currency": "MZN", "timezone": "CAT (UTC+2:00)"},
    {"name": "Myanmar", "code": "MM", "flag": "🇲🇲", "currency": "MMK", "timezone": "MMT (UTC+6:30)"},
    {"name": "Namibia", "code": "NA", "flag": "🇳🇦", "currency": "NAD", "timezone": "CAT (UTC+2:00)"},
    {"name": "Nauru", "code": "NR", "flag": "🇳🇷", "currency": "AUD", "timezone": "NRT (UTC+12:00)"},
    {"name": "Nepal", "code": "NP", "flag": "🇳🇵", "currency": "NPR", "timezone": "NPT (UTC+5:45)"},
    {"name": "Netherlands", "code": "NL", "flag": "🇳🇱", "currency": "EUR", "timezone": "CET (UTC+1:00)"},
    {"name": "New Zealand", "code": "NZ", "flag": "🇳🇿", "currency": "NZD", "timezone": "NZST (UTC+12:00)"},
    {"name": "Nicaragua", "code": "NI", "flag": "🇳🇮", "currency": "NIO", "timezone": "CST (UTC-6:00)"},
    {"name": "Niger", "code": "NE", "flag": "🇳🇪", "currency": "XOF", "timezone": "WAT (UTC+1:00)"},
    {"name": "Nigeria", "code": "NG", "flag": "🇳🇬", "currency": "NGN", "timezone": "WAT (UTC+1:00)"},
    {"name": "North Korea", "code": "KP", "flag": "🇰🇵", "currency": "KPW", "timezone": "KST (UTC+9:00)"},
    {"name": "North Macedonia", "code": "MK", "flag": "🇲🇰", "currency": "MKD", "timezone": "CET (UTC+1:00)"},
    {"name": "Norway", "code": "NO", "flag": "🇳🇴", "currency": "NOK", "timezone": "CET (UTC+1:00)"},
    {"name": "Oman", "code": "OM", "flag": "🇴🇲", "currency": "OMR", "timezone": "GST (UTC+4:00)"},
    {"name": "Pakistan", "code": "PK", "flag": "🇵🇰", "currency": "PKR", "timezone": "PKT (UTC+5:00)"},
    {"name": "Palau", "code": "PW", "flag": "🇵🇼", "currency": "USD", "timezone": "PWT (UTC+9:00)"},
    {"name": "Palestine", "code": "PS", "flag": "🇵🇸", "currency": "ILS", "timezone": "EET (UTC+2:00)"},
    {"name": "Panama", "code": "PA", "flag": "🇵🇦", "currency": "PAB", "timezone": "EST (UTC-5:00)"},
    {"name": "Papua New Guinea", "code": "PG", "flag": "🇵🇬", "currency": "PGK", "timezone": "PGT (UTC+10:00)"},
    {"name": "Paraguay", "code": "PY", "flag": "🇵🇾", "currency": "PYG", "timezone": "PYT (UTC-4:00)"},
    {"name": "Peru", "code": "PE", "flag": "🇵🇪", "currency": "PEN", "timezone": "PET (UTC-5:00)"},
    {"name": "Philippines", "code": "PH", "flag": "🇵🇭", "currency": "PHP", "timezone": "PHT (UTC+8:00)"},
    {"name": "Poland", "code": "PL", "flag": "🇵🇱", "currency": "PLN", "timezone": "CET (UTC+1:00)"},
    {"name": "Portugal", "code": "PT", "flag": "🇵🇹", "currency": "EUR", "timezone": "WET (UTC+0:00)"},
    {"name": "Qatar", "code": "QA", "flag": "🇶🇦", "currency": "QAR", "timezone": "AST (UTC+3:00)"},
    {"name": "Romania", "code": "RO", "flag": "🇷🇴", "currency": "RON", "timezone": "EET (UTC+2:00)"},
    {"name": "Russia", "code": "RU", "flag": "🇷🇺", "currency": "RUB", "timezone": "MSK (UTC+3:00)"},
    {"name": "Rwanda", "code": "RW", "flag": "🇷🇼", "currency": "RWF", "timezone": "CAT (UTC+2:00)"},
    {"name": "Saint Kitts and Nevis", "code": "KN", "flag": "🇰🇳", "currency": "XCD", "timezone": "AST (UTC-4:00)"},
    {"name": "Saint Lucia", "code": "LC", "flag": "🇱🇨", "currency": "XCD", "timezone": "AST (UTC-4:00)"},
    {"name": "Saint Vincent and the Grenadines", "code": "VC", "flag": "🇻🇨", "currency": "XCD", "timezone": "AST (UTC-4:00)"},
    {"name": "Samoa", "code": "WS", "flag": "🇼🇸", "currency": "WST", "timezone": "WST (UTC+13:00)"},
    {"name": "San Marino", "code": "SM", "flag": "🇸🇲", "currency": "EUR", "timezone": "CET (UTC+1:00)"},
    {"name": "Sao Tome and Principe", "code": "ST", "flag": "🇸🇹", "currency": "STN", "timezone": "GMT (UTC+0:00)"},
    {"name": "Saudi Arabia", "code": "SA", "flag": "🇸🇦", "currency": "SAR", "timezone": "AST (UTC+3:00)"},
    {"name": "Senegal", "code": "SN", "flag": "🇸🇳", "currency": "XOF", "timezone": "GMT (UTC+0:00)"},
    {"name": "Serbia", "code": "RS", "flag": "🇷🇸", "currency": "RSD", "timezone": "CET (UTC+1:00)"},
    {"name": "Seychelles", "code": "SC", "flag": "🇸🇨", "currency": "SCR", "timezone": "SCT (UTC+4:00)"},
    {"name": "Sierra Leone", "code": "SL", "flag": "🇸🇱", "currency": "SLE", "timezone": "GMT (UTC+0:00)"},
    {"name": "Singapore", "code": "SG", "flag": "🇸🇬", "currency": "SGD", "timezone": "SGT (UTC+8:00)"},
    {"name": "Slovakia", "code": "SK", "flag": "🇸🇰", "currency": "EUR", "timezone": "CET (UTC+1:00)"},
    {"name": "Slovenia", "code": "SI", "flag": "🇸🇮", "currency": "EUR", "timezone": "CET (UTC+1:00)"},
    {"name": "Solomon Islands", "code": "SB", "flag": "🇸🇧", "currency": "SBD", "timezone": "SBT (UTC+11:00)"},
    {"name": "Somalia", "code": "SO", "flag": "🇸🇴", "currency": "SOS", "timezone": "EAT (UTC+3:00)"},
    {"name": "South Africa", "code": "ZA", "flag": "🇿🇦", "currency": "ZAR", "timezone": "SAST (UTC+2:00)"},
    {"name": "South Korea", "code": "KR", "flag": "🇰🇷", "currency": "KRW", "timezone": "KST (UTC+9:00)"},
    {"name": "South Sudan", "code": "SS", "flag": "🇸🇸", "currency": "SSP", "timezone": "CAT (UTC+2:00)"},
    {"name": "Spain", "code": "ES", "flag": "🇪🇸", "currency": "EUR", "timezone": "CET (UTC+1:00)"},
    {"name": "Sri Lanka", "code": "LK", "flag": "🇱🇰", "currency": "LKR", "timezone": "IST (UTC+5:30)"},
    {"name": "Sudan", "code": "SD", "flag": "🇸🇩", "currency": "SDG", "timezone": "CAT (UTC+2:00)"},
    {"name": "Suriname", "code": "SR", "flag": "🇸🇷", "currency": "SRD", "timezone": "SRT (UTC-3:00)"},
    {"name": "Sweden", "code": "SE", "flag": "🇸🇪", "currency": "SEK", "timezone": "CET (UTC+1:00)"},
    {"name": "Switzerland", "code": "CH", "flag": "🇨🇭", "currency": "CHF", "timezone": "CET (UTC+1:00)"},
    {"name": "Syria", "code": "SY", "flag": "🇸🇾", "currency": "SYP", "timezone": "EET (UTC+2:00)"},
    {"name": "Tajikistan", "code": "TJ", "flag": "🇹🇯", "currency": "TJS", "timezone": "TJT (UTC+5:00)"},
    {"name": "Tanzania", "code": "TZ", "flag": "🇹🇿", "currency": "TZS", "timezone": "EAT (UTC+3:00)"},
    {"name": "Thailand", "code": "TH", "flag": "🇹🇭", "currency": "THB", "timezone": "ICT (UTC+7:00)"},
    {"name": "Timor-Leste", "code": "TL", "flag": "🇹🇱", "currency": "USD", "timezone": "TLT (UTC+9:00)"},
    {"name": "Togo", "code": "TG", "flag": "🇹🇬", "currency": "XOF", "timezone": "GMT (UTC+0:00)"},
    {"name": "Tonga", "code": "TO", "flag": "🇹🇴", "currency": "TOP", "timezone": "TOT (UTC+13:00)"},
    {"name": "Trinidad and Tobago", "code": "TT", "flag": "🇹🇹", "currency": "TTD", "timezone": "AST (UTC-4:00)"},
    {"name": "Tunisia", "code": "TN", "flag": "🇹🇳", "currency": "TND", "timezone": "CET (UTC+1:00)"},
    {"name": "Turkey", "code": "TR", "flag": "🇹🇷", "currency": "TRY", "timezone": "TRT (UTC+3:00)"},
    {"name": "Turkmenistan", "code": "TM", "flag": "🇹🇲", "currency": "TMT", "timezone": "TMT (UTC+5:00)"},
    {"name": "Tuvalu", "code": "TV", "flag": "🇹🇻", "currency": "AUD", "timezone": "TVT (UTC+12:00)"},
    {"name": "Uganda", "code": "UG", "flag": "🇺🇬", "currency": "UGX", "timezone": "EAT (UTC+3:00)"},
    {"name": "Ukraine", "code": "UA", "flag": "🇺🇦", "currency": "UAH", "timezone": "EET (UTC+2:00)"},
    {"name": "United Arab Emirates", "code": "AE", "flag": "🇦🇪", "currency": "AED", "timezone": "GST (UTC+4:00)"},
    {"name": "United Kingdom", "code": "GB", "flag": "🇬🇧", "currency": "GBP", "timezone": "GMT (UTC+0:00)"},
    {"name": "United States", "code": "US", "flag": "🇺🇸", "currency": "USD", "timezone": "EST/PST (UTC-5/UTC-8)"},
    {"name": "Uruguay", "code": "UY", "flag": "🇺🇾", "currency": "UYU", "timezone": "UYT (UTC-3:00)"},
    {"name": "Uzbekistan", "code": "UZ", "flag": "🇺🇿", "currency": "UZS", "timezone": "UZT (UTC+5:00)"},
    {"name": "Vanuatu", "code": "VU", "flag": "🇻🇺", "currency": "VUV", "timezone": "VUT (UTC+11:00)"},
    {"name": "Venezuela", "code": "VE", "flag": "🇻🇪", "currency": "VES", "timezone": "VET (UTC-4:00)"},
    {"name": "Vietnam", "code": "VN", "flag": "🇻🇳", "currency": "VND", "timezone": "ICT (UTC+7:00)"},
    {"name": "Yemen", "code": "YE", "flag": "🇾🇪", "currency": "YER", "timezone": "AST (UTC+3:00)"},
    {"name": "Zambia", "code": "ZM", "flag": "🇿🇲", "currency": "ZMW", "timezone": "CAT (UTC+2:00)"},
    {"name": "Zimbabwe", "code": "ZW", "flag": "🇿🇼", "currency": "ZWL", "timezone": "CAT (UTC+2:00)"},
]

# Quick Lookup Dictionaries
GLOBAL_COUNTRY_FLAGS = {c['name']: c['flag'] for c in COUNTRIES_195}
# Common Aliases & Variations
GLOBAL_COUNTRY_FLAGS.update({
    "USA": "🇺🇸",
    "United States of America": "🇺🇸",
    "UK": "🇬🇧",
    "Britain": "🇬🇧",
    "Great Britain": "🇬🇧",
    "UAE": "🇦🇪",
    "Emirates": "🇦🇪",
    "Czechia": "🇨🇿",
    "Türkiye": "🇹🇷",
    "Burma": "🇲🇲",
    "Vatican": "🇻🇦",
    "Vatican City": "🇻🇦",
    "DR Congo": "🇨🇩",
    "Congo": "🇨🇬",
    "South Korea": "🇰🇷",
    "Korea": "🇰🇷",
})

GLOBAL_COUNTRY_TIMEZONES = {c['name']: c['timezone'] for c in COUNTRIES_195}
GLOBAL_COUNTRY_TIMEZONES.update({
    "USA": "EST/PST (UTC-5/UTC-8)",
    "UK": "GMT/BST (UTC+0/UTC+1)",
    "UAE": "GST (UTC+4:00)",
    "Czechia": "CET (UTC+1:00)",
    "Türkiye": "TRT (UTC+3:00)",
})

def search_countries(query=""):
    """Case-insensitive search across all 195 countries by name or ISO code."""
    if not query:
        return COUNTRIES_195
    q = query.strip().lower()
    return [
        c for c in COUNTRIES_195 
        if q in c['name'].lower() or q in c['code'].lower()
    ]
