TATA_1MG_PHARMACY_CATALOG = [
    {
        'id': 1,
        'name': 'Augmentin 625 Duo Tablet',
        'salt_composition': 'Amoxycillin (500mg) + Clavulanic Acid (125mg)',
        'category': 'Antibiotics',
        'price': 185.00,
        'mrp': 223.50,
        'discount_pct': 17,
        'packaging': 'strip of 10 tablets',
        'manufacturer': 'GlaxoSmithKline Pharmaceuticals Ltd',
        'generic_name': 'Generic Amoxycillin + Clavulanate 625mg',
        'generic_price': 65.00,
        'rx_required': True,
        'rating': 4.7,
        'rating_count': 3840,
        'icon_type': 'tablets'
    },
    {
        'id': 2,
        'name': 'Pan D Capsule',
        'salt_composition': 'Pantoprazole (40mg) + Domperidone (30mg SR)',
        'category': 'Digestive Support',
        'price': 188.00,
        'mrp': 235.00,
        'discount_pct': 20,
        'packaging': 'strip of 15 capsules',
        'manufacturer': 'Alkem Laboratories Ltd',
        'generic_name': 'Generic Pantoprazole 40mg + Domperidone 30mg SR',
        'generic_price': 60.00,
        'rx_required': True,
        'rating': 4.8,
        'rating_count': 5120,
        'icon_type': 'capsules'
    },
    {
        'id': 3,
        'name': 'Dolo 650 Tablet',
        'salt_composition': 'Paracetamol / Acetaminophen (650mg)',
        'category': 'Pain Relief',
        'price': 28.00,
        'mrp': 34.00,
        'discount_pct': 18,
        'packaging': 'strip of 15 tablets',
        'manufacturer': 'Micro Labs Ltd',
        'generic_name': 'Generic Paracetamol 650mg Tablet',
        'generic_price': 12.00,
        'rx_required': False,
        'rating': 4.9,
        'rating_count': 12400,
        'icon_type': 'tablets'
    },
    {
        'id': 4,
        'name': 'Shelcal 500 Tablet',
        'salt_composition': 'Elemental Calcium (500mg) + Vitamin D3 (250 IU)',
        'category': 'Vitamins',
        'price': 115.00,
        'mrp': 144.00,
        'discount_pct': 20,
        'packaging': 'strip of 15 tablets',
        'manufacturer': 'Torrent Pharmaceuticals Ltd',
        'generic_name': 'Generic Calcium 500mg + Vitamin D3',
        'generic_price': 45.00,
        'rx_required': False,
        'rating': 4.8,
        'rating_count': 8950,
        'icon_type': 'tablets'
    },
    {
        'id': 5,
        'name': 'Glycomet-GP 2 Forte Tablet PR',
        'salt_composition': 'Glimepiride (2mg) + Metformin Hydrochloride (1000mg PR)',
        'category': 'Diabetes',
        'price': 198.00,
        'mrp': 248.00,
        'discount_pct': 20,
        'packaging': 'strip of 15 tablets',
        'manufacturer': 'USV Ltd',
        'generic_name': 'Generic Glimepiride 2mg + Metformin 1000mg SR',
        'generic_price': 72.00,
        'rx_required': True,
        'rating': 4.7,
        'rating_count': 4150,
        'icon_type': 'tablets'
    },
    {
        'id': 6,
        'name': 'Telma 40 Tablet',
        'salt_composition': 'Telmisartan (40mg)',
        'category': 'Cardiac',
        'price': 228.00,
        'mrp': 285.00,
        'discount_pct': 20,
        'packaging': 'strip of 30 tablets',
        'manufacturer': 'Glenmark Pharmaceuticals Ltd',
        'generic_name': 'Generic Telmisartan 40mg Tablet',
        'generic_price': 75.00,
        'rx_required': True,
        'rating': 4.8,
        'rating_count': 6300,
        'icon_type': 'tablets'
    },
    {
        'id': 7,
        'name': 'Becosules Z Capsule',
        'salt_composition': 'B-Complex Forte + Vitamin C (50mg) + Elemental Zinc (41.4mg)',
        'category': 'Vitamins',
        'price': 42.00,
        'mrp': 52.00,
        'discount_pct': 19,
        'packaging': 'strip of 20 capsules',
        'manufacturer': 'Pfizer Ltd',
        'generic_name': 'Generic Vitamin B-Complex with Zinc Capsule',
        'generic_price': 18.00,
        'rx_required': False,
        'rating': 4.9,
        'rating_count': 15200,
        'icon_type': 'capsules'
    },
    {
        'id': 8,
        'name': 'Allegra 120mg Tablet',
        'salt_composition': 'Fexofenadine Hydrochloride (120mg)',
        'category': 'Cold & Flu',
        'price': 182.00,
        'mrp': 228.00,
        'discount_pct': 20,
        'packaging': 'strip of 10 tablets',
        'manufacturer': 'Sanofi India Ltd',
        'generic_name': 'Generic Fexofenadine 120mg Tablet',
        'generic_price': 55.00,
        'rx_required': False,
        'rating': 4.7,
        'rating_count': 4890,
        'icon_type': 'tablets'
    },
    {
        'id': 9,
        'name': 'Ascoril D Plus Syrup',
        'salt_composition': 'Dextromethorphan (10mg) + Phenylephrine (5mg) + Chlorpheniramine (2mg)',
        'category': 'Cold & Flu',
        'price': 108.00,
        'mrp': 135.00,
        'discount_pct': 20,
        'packaging': 'bottle of 100 ml syrup',
        'manufacturer': 'Glenmark Pharmaceuticals Ltd',
        'generic_name': 'Generic Cough Relief Sugar-Free Syrup',
        'generic_price': 42.00,
        'rx_required': False,
        'rating': 4.6,
        'rating_count': 3710,
        'icon_type': 'syrup'
    },
    {
        'id': 10,
        'name': 'Azithral 500 Tablet',
        'salt_composition': 'Azithromycin (500mg)',
        'category': 'Antibiotics',
        'price': 105.00,
        'mrp': 132.00,
        'discount_pct': 20,
        'packaging': 'strip of 5 tablets',
        'manufacturer': 'Alembic Pharmaceuticals Ltd',
        'generic_name': 'Generic Azithromycin 500mg Tablet',
        'generic_price': 38.00,
        'rx_required': True,
        'rating': 4.7,
        'rating_count': 5600,
        'icon_type': 'tablets'
    },
    {
        'id': 11,
        'name': 'Liv.52 DS Tablet',
        'salt_composition': 'Ayurvedic Hepato-Protective Herbs (Himsra, Kasani, Mandur Bhasma)',
        'category': 'Ayurveda',
        'price': 185.00,
        'mrp': 215.00,
        'discount_pct': 14,
        'packaging': 'bottle of 60 tablets',
        'manufacturer': 'The Himalaya Wellness Company',
        'generic_name': 'Generic Ayurvedic Liver Care Herbal Formulation',
        'generic_price': 95.00,
        'rx_required': False,
        'rating': 4.9,
        'rating_count': 21500,
        'icon_type': 'tablets'
    },
    {
        'id': 12,
        'name': 'Volini Pain Relief Gel',
        'salt_composition': 'Diclofenac Diethylamine (1.16%) + Linseed Oil + Methyl Salicylate + Menthol',
        'category': 'Pain Relief',
        'price': 132.00,
        'mrp': 165.00,
        'discount_pct': 20,
        'packaging': 'tube of 50 gm gel',
        'manufacturer': 'Sun Pharma Laboratories Ltd',
        'generic_name': 'Generic Diclofenac Topical Pain Gel',
        'generic_price': 48.00,
        'rx_required': False,
        'rating': 4.8,
        'rating_count': 9400,
        'icon_type': 'ointment'
    },
    {
        'id': 13,
        'name': 'Ecosprin 75 Tablet',
        'salt_composition': 'Aspirin / Acetylsalicylic Acid (75mg Gastro-Resistant)',
        'category': 'Cardiac',
        'price': 5.20,
        'mrp': 6.20,
        'discount_pct': 16,
        'packaging': 'strip of 14 tablets',
        'manufacturer': 'USV Ltd',
        'generic_name': 'Generic Low-Dose Aspirin 75mg',
        'generic_price': 2.50,
        'rx_required': True,
        'rating': 4.8,
        'rating_count': 8200,
        'icon_type': 'tablets'
    },
    {
        'id': 14,
        'name': 'Atorva 20 Tablet',
        'salt_composition': 'Atorvastatin (20mg)',
        'category': 'Cardiac',
        'price': 214.00,
        'mrp': 268.00,
        'discount_pct': 20,
        'packaging': 'strip of 15 tablets',
        'manufacturer': 'Zydus Healthcare Ltd',
        'generic_name': 'Generic Atorvastatin 20mg Tablet',
        'generic_price': 65.00,
        'rx_required': True,
        'rating': 4.7,
        'rating_count': 4500,
        'icon_type': 'tablets'
    },
    {
        'id': 15,
        'name': 'Supradyn Daily Multivitamin Tablet',
        'salt_composition': 'Multivitamins + Minerals + Trace Elements (Zinc, Copper, Iron)',
        'category': 'Vitamins',
        'price': 54.00,
        'mrp': 64.00,
        'discount_pct': 16,
        'packaging': 'strip of 15 tablets',
        'manufacturer': 'Bayer Pharmaceuticals Pvt Ltd',
        'generic_name': 'Generic Daily Multivitamin & Mineral Compound',
        'generic_price': 25.00,
        'rx_required': False,
        'rating': 4.8,
        'rating_count': 11800,
        'icon_type': 'tablets'
    },
    {
        'id': 16,
        'name': 'Neurobion Forte Tablet',
        'salt_composition': 'Vitamin B1 + B2 + B3 + B5 + B6 + B12 (15mcg)',
        'category': 'Vitamins',
        'price': 36.00,
        'mrp': 43.00,
        'discount_pct': 16,
        'packaging': 'strip of 30 tablets',
        'manufacturer': 'Procter & Gamble Health Ltd',
        'generic_name': 'Generic Vitamin B-Complex with Mecobalamin',
        'generic_price': 15.00,
        'rx_required': False,
        'rating': 4.9,
        'rating_count': 18400,
        'icon_type': 'tablets'
    },
    {
        'id': 17,
        'name': 'Celin 500 Chewable Tablet',
        'salt_composition': 'Vitamin C (Ascorbic Acid 500mg)',
        'category': 'Vitamins',
        'price': 38.00,
        'mrp': 45.00,
        'discount_pct': 16,
        'packaging': 'strip of 25 chewable tablets',
        'manufacturer': 'Abbott Healthcare Pvt Ltd',
        'generic_name': 'Generic Ascorbic Acid 500mg Chewable',
        'generic_price': 16.00,
        'rx_required': False,
        'rating': 4.9,
        'rating_count': 14200,
        'icon_type': 'tablets'
    },
    {
        'id': 18,
        'name': 'Montair-LC Tablet',
        'salt_composition': 'Montelukast (10mg) + Levocetirizine (5mg)',
        'category': 'Cold & Flu',
        'price': 185.00,
        'mrp': 232.00,
        'discount_pct': 20,
        'packaging': 'strip of 10 tablets',
        'manufacturer': 'Cipla Ltd',
        'generic_name': 'Generic Montelukast 10mg + Levocetirizine 5mg',
        'generic_price': 58.00,
        'rx_required': True,
        'rating': 4.7,
        'rating_count': 6900,
        'icon_type': 'tablets'
    },
    {
        'id': 19,
        'name': 'Betadine 10% Ointment',
        'salt_composition': 'Povidone Iodine (10% w/w Antiseptic)',
        'category': 'First Aid',
        'price': 110.00,
        'mrp': 138.00,
        'discount_pct': 20,
        'packaging': 'tube of 20 gm ointment',
        'manufacturer': 'Win-Medicare Pvt Ltd',
        'generic_name': 'Generic Povidone Iodine 10% Ointment',
        'generic_price': 40.00,
        'rx_required': False,
        'rating': 4.8,
        'rating_count': 8700,
        'icon_type': 'ointment'
    },
    {
        'id': 20,
        'name': 'Janumet 50mg/500mg Tablet',
        'salt_composition': 'Sitagliptin (50mg) + Metformin Hydrochloride (500mg)',
        'category': 'Diabetes',
        'price': 328.00,
        'mrp': 410.00,
        'discount_pct': 20,
        'packaging': 'strip of 15 tablets',
        'manufacturer': 'MSD Pharmaceuticals Pvt Ltd',
        'generic_name': 'Generic Sitagliptin 50mg + Metformin 500mg',
        'generic_price': 110.00,
        'rx_required': True,
        'rating': 4.8,
        'rating_count': 3200,
        'icon_type': 'tablets'
    },
    {
        'id': 21,
        'name': 'Gelusil MPS Antacid Syrup',
        'salt_composition': 'Aluminium Hydroxide + Magnesium Hydroxide + Simethicone',
        'category': 'Digestive Support',
        'price': 120.00,
        'mrp': 145.00,
        'discount_pct': 17,
        'packaging': 'bottle of 200 ml mint syrup',
        'manufacturer': 'Pfizer Ltd',
        'generic_name': 'Generic Antacid & Antiflatulent Mint Suspension',
        'generic_price': 45.00,
        'rx_required': False,
        'rating': 4.8,
        'rating_count': 9900,
        'icon_type': 'syrup'
    },
    {
        'id': 22,
        'name': 'Combiflam Tablet',
        'salt_composition': 'Ibuprofen (400mg) + Paracetamol (325mg)',
        'category': 'Pain Relief',
        'price': 42.00,
        'mrp': 51.00,
        'discount_pct': 18,
        'packaging': 'strip of 20 tablets',
        'manufacturer': 'Sanofi India Ltd',
        'generic_name': 'Generic Ibuprofen 400mg + Paracetamol 325mg',
        'generic_price': 16.00,
        'rx_required': False,
        'rating': 4.8,
        'rating_count': 14300,
        'icon_type': 'tablets'
    },
    {
        'id': 23,
        'name': 'Omez 20 Capsule',
        'salt_composition': 'Omeprazole (20mg)',
        'category': 'Digestive Support',
        'price': 58.00,
        'mrp': 72.00,
        'discount_pct': 19,
        'packaging': 'strip of 20 capsules',
        'manufacturer': "Dr. Reddy's Laboratories Ltd",
        'generic_name': 'Generic Omeprazole 20mg Capsule',
        'generic_price': 20.00,
        'rx_required': False,
        'rating': 4.8,
        'rating_count': 7800,
        'icon_type': 'capsules'
    },
    {
        'id': 24,
        'name': 'Amlong 5 Tablet',
        'salt_composition': 'Amlodipine Besylate (5mg)',
        'category': 'Cardiac',
        'price': 38.00,
        'mrp': 48.00,
        'discount_pct': 21,
        'packaging': 'strip of 15 tablets',
        'manufacturer': 'Micro Labs Ltd',
        'generic_name': 'Generic Amlodipine 5mg Tablet',
        'generic_price': 12.00,
        'rx_required': True,
        'rating': 4.7,
        'rating_count': 5100,
        'icon_type': 'tablets'
    },
    {
        'id': 25,
        'name': 'Zingavita Multivitamin Gummies',
        'salt_composition': 'Vitamin A, C, D3, E, Zinc, Iodine & Elderberry Extract',
        'category': 'Vitamins',
        'price': 379.00,
        'mrp': 499.00,
        'discount_pct': 24,
        'packaging': 'bottle of 60 strawberry gummies',
        'manufacturer': 'Zingavita Consumer Health',
        'generic_name': 'Generic Multivitamin Chewable Pectin Gummies',
        'generic_price': 160.00,
        'rx_required': False,
        'rating': 4.9,
        'rating_count': 4200,
        'icon_type': 'gummies'
    },
    {
        'id': 26,
        'name': 'Meftal-Spas Tablet',
        'salt_composition': 'Mefenamic Acid (250mg) + Dicyclomine Hydrochloride (10mg)',
        'category': 'Pain Relief',
        'price': 48.00,
        'mrp': 58.00,
        'discount_pct': 17,
        'packaging': 'strip of 10 tablets',
        'manufacturer': 'Blue Cross Laboratories Ltd',
        'generic_name': 'Generic Mefenamic Acid + Dicyclomine Spas Relief',
        'generic_price': 18.00,
        'rx_required': True,
        'rating': 4.8,
        'rating_count': 9100,
        'icon_type': 'tablets'
    },
    {
        'id': 27,
        'name': 'Vicks Vaporub Balm',
        'salt_composition': 'Camphor (5.26%) + Menthol (2.82%) + Eucalyptus Oil (1.33%)',
        'category': 'Cold & Flu',
        'price': 145.00,
        'mrp': 170.00,
        'discount_pct': 15,
        'packaging': 'jar of 50 ml balm',
        'manufacturer': 'Procter & Gamble Hygiene & Health Care Ltd',
        'generic_name': 'Generic Herbal Eucalyptus & Menthol Chest Rub',
        'generic_price': 65.00,
        'rx_required': False,
        'rating': 4.9,
        'rating_count': 24000,
        'icon_type': 'ointment'
    },
    {
        'id': 28,
        'name': 'Dabur Chyawanprash Immunity Booster',
        'salt_composition': 'Amla (Indian Gooseberry) + 40+ Ayurvedic Medicinal Herbs & Honey',
        'category': 'Ayurveda',
        'price': 349.00,
        'mrp': 425.00,
        'discount_pct': 18,
        'packaging': 'jar of 1 kg herbal paste',
        'manufacturer': 'Dabur India Ltd',
        'generic_name': 'Generic Traditional Ayurvedic Chyawanprash Formulation',
        'generic_price': 190.00,
        'rx_required': False,
        'rating': 4.9,
        'rating_count': 19500,
        'icon_type': 'syrup'
    },
    {
        'id': 29,
        'name': 'Accu-Chek Active Blood Glucose Test Strips',
        'salt_composition': '50 Sterile Test Strips for Blood Glucose Measurement',
        'category': 'Diabetes',
        'price': 879.00,
        'mrp': 1099.00,
        'discount_pct': 20,
        'packaging': 'box of 50 test strips',
        'manufacturer': 'Roche Diagnostics India Pvt Ltd',
        'generic_name': 'Generic Glucometer Testing Strips Box of 50',
        'generic_price': 450.00,
        'rx_required': False,
        'rating': 4.8,
        'rating_count': 16300,
        'icon_type': 'tablets'
    },
    {
        'id': 30,
        'name': 'Tata 1mg Multivitamin with Probiotics',
        'salt_composition': '18 Essential Multivitamins & Minerals with L. Acidophilus Probiotic Blend',
        'category': 'Vitamins',
        'price': 399.00,
        'mrp': 599.00,
        'discount_pct': 33,
        'packaging': 'bottle of 60 vegetarian tablets',
        'manufacturer': 'Tata 1mg Healthcare Direct',
        'generic_name': 'Tata 1mg Exclusive Laboratory Formulation',
        'generic_price': 399.00,
        'rx_required': False,
        'rating': 4.9,
        'rating_count': 8800,
        'icon_type': 'tablets'
    }
]

TATA_1MG_MONOGRAPHS = {
    'augmentin 625 duo tablet': {
        'drug_name': 'Augmentin 625 Duo Tablet',
        'salt_composition': 'Amoxycillin (500mg) + Clavulanic Acid (125mg)',
        'manufacturer': 'GlaxoSmithKline Pharmaceuticals Ltd',
        'category': 'Antibiotics',
        'description': 'Augmentin 625 Duo Tablet is a penicillin-type antibiotic that helps your body fight infections caused by bacteria. It is used to treat infections of the lungs (e.g., pneumonia), ear, nasal sinus, urinary tract, skin, and soft tissue.',
        'primary_use': 'Bacterial infections of the respiratory tract, ear, nose, throat, skin, and urinary tract.',
        'mechanism_of_action': 'Amoxycillin prevents the formation of the bacterial protective covering which is essential for the survival of bacteria. Clavulanic Acid works as a beta-lactamase inhibitor which blocks the enzyme that bacteria produce to resist Amoxycillin.',
        'common_side_effects': ['Nausea', 'Diarrhea', 'Vomiting', 'Skin rash', 'Fungal infections of mouth or vagina'],
        'caution': 'Complete the full course even if you feel better. Take with a meal to avoid stomach upset. Avoid if allergic to penicillins or cephalosporins.',
        'safety_advices': {
            'alcohol': {'status': 'Caution', 'desc': 'Avoid alcohol as it can increase side effects like dizziness and dehydration.'},
            'pregnancy': {'status': 'Safe if prescribed', 'desc': 'Generally considered safe during pregnancy when prescribed by a doctor.'},
            'breastfeeding': {'status': 'Safe if prescribed', 'desc': 'Small amounts may pass into breast milk; monitor the infant for diarrhea.'},
            'driving': {'status': 'Caution', 'desc': 'May cause dizziness or allergic reactions which can impair driving capability.'},
            'kidney': {'status': 'Caution', 'desc': 'Dose adjustment may be required in patients with severe kidney impairment.'},
            'liver': {'status': 'Caution', 'desc': 'Use with caution in patients with preexisting liver conditions; periodic LFT recommended.'}
        },
        'generic_substitute': {
            'name': 'Generic Amoxycillin + Potassium Clavulanate 625mg',
            'price': 65.00,
            'orig_price': 185.00,
            'savings_pct': 65
        }
    },
    'pan d capsule': {
        'drug_name': 'Pan D Capsule',
        'salt_composition': 'Pantoprazole (40mg) + Domperidone (30mg SR)',
        'manufacturer': 'Alkem Laboratories Ltd',
        'category': 'Digestive Support',
        'description': 'Pan D Capsule is a prescription medicine used to treat gastroesophageal reflux disease (Acid reflux) and peptic ulcer disease by relieving symptoms of acidity such as heartburn, stomach pain, or irritation.',
        'primary_use': 'Gastroesophageal reflux disease (GERD), acid peptic ulcers, heartburn, and nausea/vomiting associated with gastritis.',
        'mechanism_of_action': 'Pantoprazole is a proton pump inhibitor (PPI) that reduces stomach acid production. Domperidone is a prokinetic agent that accelerates upper digestive tract motility, preventing stomach contents from flowing back into the esophagus.',
        'common_side_effects': ['Dry mouth', 'Diarrhea', 'Headache', 'Dizziness', 'Flatulence'],
        'caution': 'Take 30 to 60 minutes before breakfast. Prolonged use may decrease magnesium and vitamin B12 absorption; monitor periodically.',
        'safety_advices': {
            'alcohol': {'status': 'Unsafe', 'desc': 'Alcohol stimulates acid production and worsens GERD symptoms.'},
            'pregnancy': {'status': 'Consult Doctor', 'desc': 'Consult your doctor before taking Pan D during pregnancy.'},
            'breastfeeding': {'status': 'Consult Doctor', 'desc': 'Small amounts may pass into breast milk. Use only if clearly advised by your physician.'},
            'driving': {'status': 'Safe', 'desc': 'Does not typically affect alertness or driving ability.'},
            'kidney': {'status': 'Safe', 'desc': 'Generally safe in mild-to-moderate kidney disease without dose reduction.'},
            'liver': {'status': 'Caution', 'desc': 'Caution advised in severe liver impairment; monitor liver transaminases.'}
        },
        'generic_substitute': {
            'name': 'Generic Pantoprazole 40mg + Domperidone 30mg SR',
            'price': 60.00,
            'orig_price': 188.00,
            'savings_pct': 68
        }
    },
    'dolo 650 tablet': {
        'drug_name': 'Dolo 650 Tablet',
        'salt_composition': 'Paracetamol / Acetaminophen (650mg)',
        'manufacturer': 'Micro Labs Ltd',
        'category': 'Pain Relief',
        'description': 'Dolo 650 Tablet is an effective fever-reducing (antipyretic) and pain-relieving (analgesic) medicine used widely for headaches, toothache, muscle aches, post-vaccination fever, and general body pain.',
        'primary_use': 'Fever reduction, headache, toothache, muscle pain, post-surgical pain, and cold-associated fever.',
        'mechanism_of_action': 'Paracetamol inhibits cyclooxygenase (COX) enzymes in the central nervous system, reducing prostaglandin synthesis which signals pain and elevates body temperature in the hypothalamus.',
        'common_side_effects': ['Nausea (rare)', 'Allergic skin rash (rare)', 'Liver toxicity only in massive overdose'],
        'caution': 'Do not exceed 4 grams (4000mg) in 24 hours. Avoid combining with other paracetamol-containing cough/cold medicines to prevent accidental hepatotoxicity.',
        'safety_advices': {
            'alcohol': {'status': 'Unsafe', 'desc': 'Combining alcohol with paracetamol significantly increases the risk of severe liver damage.'},
            'pregnancy': {'status': 'Safe if prescribed', 'desc': 'Regarded as the safest analgesic/antipyretic throughout pregnancy under therapeutic dosages.'},
            'breastfeeding': {'status': 'Safe', 'desc': 'Passes into breast milk in very minimal quantities without adverse infant effects.'},
            'driving': {'status': 'Safe', 'desc': 'Does not cause sedation or impair concentration.'},
            'kidney': {'status': 'Safe', 'desc': 'Safe in renal impairment under normal spacing intervals (minimum 6 hours apart).'},
            'liver': {'status': 'Caution', 'desc': 'Severe caution in active cirrhosis or chronic hepatitis; dosage limit strictly 2g/day.'}
        },
        'generic_substitute': {
            'name': 'Generic Paracetamol 650mg Tablet',
            'price': 12.00,
            'orig_price': 28.00,
            'savings_pct': 57
        }
    }
}

MEDICINE_LIST = []

try:
    from medicine_catalog import (
        load_all_medicines,
        get_top_recommended,
        search_medicines,
        find_medicine_by_name_or_id,
        ALL_MEDICINES
    )
except Exception as _e_med_import:
    print(f"⚠️ Warning loading medicine_catalog: {_e_med_import}")
    load_all_medicines = lambda: []
    get_top_recommended = lambda limit=32: []
    search_medicines = lambda **kwargs: {'total': 0, 'medicines': []}
    find_medicine_by_name_or_id = lambda name: None
    ALL_MEDICINES = []

PINCODE_CACHE = {}

KNOWN_PINCODE_MAPPING = {
    '110001': {'city': 'New Delhi', 'district': 'Central Delhi', 'state': 'Delhi'},
    '400001': {'city': 'Mumbai', 'district': 'Mumbai', 'state': 'Maharashtra'},
    '560001': {'city': 'Bengaluru', 'district': 'Bengaluru Urban', 'state': 'Karnataka'},
    '500001': {'city': 'Hyderabad', 'district': 'Hyderabad', 'state': 'Telangana'},
    '600001': {'city': 'Chennai', 'district': 'Chennai', 'state': 'Tamil Nadu'},
    '700001': {'city': 'Kolkata', 'district': 'Kolkata', 'state': 'West Bengal'},
    '380001': {'city': 'Ahmedabad', 'district': 'Ahmedabad', 'state': 'Gujarat'},
    '411001': {'city': 'Pune', 'district': 'Pune', 'state': 'Maharashtra'},
    '122001': {'city': 'Gurgaon', 'district': 'Gurugram', 'state': 'Haryana'},
    '201301': {'city': 'Noida', 'district': 'Gautam Buddha Nagar', 'state': 'Uttar Pradesh'},
    '226001': {'city': 'Lucknow', 'district': 'Lucknow', 'state': 'Uttar Pradesh'},
    '302001': {'city': 'Jaipur', 'district': 'Jaipur', 'state': 'Rajasthan'},
    '800001': {'city': 'Patna', 'district': 'Patna', 'state': 'Bihar'},
    '160017': {'city': 'Chandigarh', 'district': 'Chandigarh', 'state': 'Chandigarh'},
    '452001': {'city': 'Indore', 'district': 'Indore', 'state': 'Madhya Pradesh'},
    '682001': {'city': 'Kochi', 'district': 'Ernakulam', 'state': 'Kerala'},
}

